services:
  postgres-taller:
    image: postgres:16
    container_name: postgres-taller
    environment:
      POSTGRES_DB: taller_db
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_taller_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taller_user -d taller_db"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - taller-net

  auth-admin-users:
    build:
      context: ./backend/auth-admin-users
    container_name: auth-admin-users
    environment:
      SERVER_PORT: 8081
      POSTGRES_HOST: postgres-taller
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: taller_db
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_pass
      JWT_SECRET: ${JWT_SECRET:-bXktc3VwZXItc2VjcmV0LWtleS10YWxsZXItcGFyY2lhbC0yMDI2}
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres-taller:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - taller-net

  taller-mecanico:
    build:
      context: ./backend/taller-mecanico
    container_name: taller-mecanico
    environment:
      SERVER_PORT: 8082
      POSTGRES_HOST: postgres-taller
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: taller_db
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_pass
      JWT_SECRET: ${JWT_SECRET:-bXktc3VwZXItc2VjcmV0LWtleS10YWxsZXItcGFyY2lhbC0yMDI2}
    depends_on:
      postgres-taller:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - taller-net

  frontend:
    build:
      context: ./frontend
    container_name: taller-frontend
    ports:
      - "4200:80"
    depends_on:
      - auth-admin-users
      - taller-mecanico
    networks:
      - taller-net

volumes:
  postgres_taller_data:

networks:
  taller-net:
